import type { Env } from "./types";
import { GitHubRepo } from "./github";
import { TelegramClient } from "./telegram";
import { GeminiClient } from "./gemini";
import { createConversation, getConversation, getUserMemory, setUserMemory } from "./memory";
import { describeZip, listConversationFiles, listAllConversations, storeConversationFile } from "./files";
import { extensionOf, mimeTypeForExtension, parseCommand } from "./utils";

async function replyTrue(telegram: TelegramClient, chatId: number, text: string): Promise<boolean> {
  await telegram.sendMessage(chatId, text);
  return true;
}

export async function handleCommand(
  parsed: { command: string; args: string },
  ctx: { repo: GitHubRepo; telegram: TelegramClient; gemini: GeminiClient; env: Env; chatId: number; userId: string; updateId: number }
): Promise<boolean> {
  const { command, args } = parsed;
  switch (command) {
    case "new": {
      await createConversation(ctx.repo, ctx.userId, ctx.chatId, args || "New conversation");
      return replyTrue(ctx.telegram, ctx.chatId, "Percakapan baru dibuat dan dipilih sebagai percakapan aktif.");
    }
    case "conversations": {
      const user = await getUserMemory(ctx.repo, ctx.userId);
      const ids = await listAllConversations(ctx.repo, ctx.userId);
      if (!ids.length) return replyTrue(ctx.telegram, ctx.chatId, "Belum ada percakapan tersimpan.");
      const lines = ids.slice(-50).reverse().map((x, i) => `${i + 1}. ${x.id}${x.id === user.activeConversationId ? " [aktif]" : ""}`);
      return replyTrue(ctx.telegram, ctx.chatId, `Percakapan tersimpan:\n${lines.join("\n")}\n\nGunakan /select <conversation_id>.`);
    }
    case "select": {
      const id = args.trim();
      if (!id) return replyTrue(ctx.telegram, ctx.chatId, "Gunakan: /select <conversation_id>");
      const conv = await getConversation(ctx.repo, id);
      if (!conv || conv.userId !== ctx.userId) return replyTrue(ctx.telegram, ctx.chatId, "Percakapan tidak ditemukan.");
      const user = await getUserMemory(ctx.repo, ctx.userId);
      user.activeConversationId = conv.id;
      if (!user.conversationIds.includes(conv.id)) user.conversationIds.push(conv.id);
      user.updatedAt = new Date().toISOString();
      await setUserMemory(ctx.repo, user);
      return replyTrue(ctx.telegram, ctx.chatId, `Percakapan aktif: ${conv.id}`);
    }
    case "files": {
      const user = await getUserMemory(ctx.repo, ctx.userId);
      const conversationId = user.activeConversationId;
      if (!conversationId) return replyTrue(ctx.telegram, ctx.chatId, "Belum ada percakapan aktif.");
      const files = await listConversationFiles(ctx.repo, conversationId);
      if (!files.length) return replyTrue(ctx.telegram, ctx.chatId, "Belum ada file pada percakapan aktif.");
      const lines = files.slice(-100).reverse().map((f, i) => `${i + 1}. [${f.kind}] ${f.name}${f.size != null ? ` (${f.size} bytes)` : ""}`);
      return replyTrue(ctx.telegram, ctx.chatId, `File tersimpan:\n${lines.join("\n")}\n\nGunakan /send <nama_file> atau /discuss <nama_file>.`);
    }
    case "generate": {
      const parts = args.trim().split(/\s+/);
      const ext = (parts.shift() || "").replace(/^\./, "").toLowerCase();
      const prompt = parts.join(" ").trim();
      if (!ext || !prompt) return replyTrue(ctx.telegram, ctx.chatId, "Gunakan: /generate <format> <deskripsi>\nContoh: /generate md Dokumentasi API Neuralis");
      const user = await getUserMemory(ctx.repo, ctx.userId);
      let conversation = user.activeConversationId ? await getConversation(ctx.repo, user.activeConversationId) : null;
      if (!conversation) conversation = await createConversation(ctx.repo, ctx.userId, ctx.chatId, "Generated files");
      const result = await ctx.gemini.generateFile(ext, prompt);
      const maxBytes = Number(ctx.env.MAX_FILE_BYTES) || 8 * 1024 * 1024;
      const stored = await storeConversationFile(ctx.repo, conversation.id, "made", result.fileName, result.mimeType, result.bytes, maxBytes, `update_${ctx.updateId}`);
      await ctx.telegram.sendDocument(ctx.chatId, stored.name, result.bytes, stored.mimeType, `Generated by Neuralis: ${stored.name}`);
      return true;
    }
    case "send": {
      const name = args.trim();
      if (!name) return replyTrue(ctx.telegram, ctx.chatId, "Gunakan: /send <nama_file>");
      const user = await getUserMemory(ctx.repo, ctx.userId);
      const conversationId = user.activeConversationId;
      if (!conversationId) return replyTrue(ctx.telegram, ctx.chatId, "Belum ada percakapan aktif.");
      const files = await listConversationFiles(ctx.repo, conversationId);
      const chosen = files.slice().reverse().find((f) => f.name === name) ?? files.slice().reverse().find((f) => f.name.toLowerCase().includes(name.toLowerCase()));
      if (!chosen) return replyTrue(ctx.telegram, ctx.chatId, `File tidak ditemukan: ${name}`);
      const bytes = await ctx.repo.read(chosen.path);
      if (!bytes) return replyTrue(ctx.telegram, ctx.chatId, "File tidak dapat dibaca dari GitHub.");
      await ctx.telegram.sendDocument(ctx.chatId, chosen.name, bytes, mimeTypeForExtension(extensionOf(chosen.name)));
      return true;
    }
    case "discuss": {
      const name = args.trim();
      if (!name) return replyTrue(ctx.telegram, ctx.chatId, "Gunakan: /discuss <nama_file>");
      const user = await getUserMemory(ctx.repo, ctx.userId);
      const conversationId = user.activeConversationId;
      if (!conversationId) return replyTrue(ctx.telegram, ctx.chatId, "Belum ada percakapan aktif.");
      const conv = await getConversation(ctx.repo, conversationId);
      if (!conv) return replyTrue(ctx.telegram, ctx.chatId, "Percakapan aktif tidak ditemukan.");
      const files = await listConversationFiles(ctx.repo, conv.id);
      const chosen = files.slice().reverse().find((f) => f.name === name) ?? files.slice().reverse().find((f) => f.name.toLowerCase().includes(name.toLowerCase()));
      if (!chosen) return replyTrue(ctx.telegram, ctx.chatId, `File tidak ditemukan: ${name}`);
      conv.discussedFilePath = chosen.path;
      conv.updatedAt = new Date().toISOString();
      await ctx.repo.upsertJson(`Conversation/${conv.id}.json`, conv, `Select file ${chosen.name}`);
      let message = `File diskusi dipilih: ${chosen.name}. Pesan berikutnya akan dikirim ke AI bersama file ini.`;
      const bytes = await ctx.repo.read(chosen.path);
      if (bytes && extensionOf(chosen.name) === "zip") message += `\n\n${await describeZip(bytes)}`;
      return replyTrue(ctx.telegram, ctx.chatId, message);
    }
    case "help":
      return replyTrue(ctx.telegram, ctx.chatId, [
        "Perintah Neuralis:",
        "/new [judul] - buat percakapan baru",
        "/conversations - daftar percakapan",
        "/select <id> - pilih percakapan",
        "/files - daftar file pada percakapan aktif",
        "/generate <format> <prompt> - buat file dengan AI",
        "/send <nama_file> - kirim file tersimpan",
        "/discuss <nama_file> - pilih file untuk dibahas",
        "",
        "Obrolan biasa tidak memerlukan slash command."
      ].join("\n"));
    default:
      return false;
  }
}

export function commandFromText(text: string): { command: string; args: string } | null {
  return parseCommand(text);
}
